language: node_js
node_js: 'node'
script: 'npm run ci'
addons:
  code_climate:
    repo_token: '6e3b879f302a15c1639b5e285e72981dc6d69127edacd3242dbe76244e114f43'
notifications:
  email: false
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
